import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import dynamic from 'next/dynamic';
import { Providers } from "../providers";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }

}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };

}>) {

  const CrispWithNoSSR = dynamic(
    () => import('../../components/crisp'),
  )


  const messages = await getMessages();


  return (
    <html lang={locale}>

      <body className={inter.className}>
        <Providers>
          <CrispWithNoSSR />
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}
